### ISSUE TITLE
Guidence for complete system that does sending, receiving and consuming

### ISSUE THREAD

**Issue by rhiaro** [csarven/ldn#11]
Maybe this is useful in an implementation section; at least worth thinking about

**Comment by csarven** [comment]
What do you mean by guidance exactly besides examples and the considerations?

**Comment by rhiaro** [comment]
Maybe this is a primer type thing, or implementation guidelines.

**Comment by csarven** [comment]
If #4 is available, consider incorporating that.

**Comment by akuckartz** [comment]
:+1:

**Comment by rhiaro** [comment]
I'll do this in SWP
