### ISSUE TITLE
Namespace location

### ISSUE THREAD

**Issue by csarven** [csarven/ldn#13]
Original implementations of LDN used/s the `solid-terms` namespace e.g., the `inbox` property which points to the Inbox URL. The spec considers to move this over to the `ldp` namespace. This issue is intended to have consensus on this proposal.

**Comment by csarven** [comment]
Reasons to use the ldp namespace:
- Closely aligned with the concepts in the LDP vocabulary (without requiring an LDP implementation)
- Reuse of widely used namespace
- Interest to the LDN-Next CG.

Reasons against:
- LDN is a specialisation / particular category of applications and behaviours - `solid-terms` is more suitable in this case. Plus, additional terms/behaviours (e.g., notification 'read') would be more suitable somewhere other than the ldp ns - (this is not to imply that those additions will have to be in the same ns as the core LDN)

**Comment by melvincarvalho** [comment]
If LDP is a webized version of a file system, typically file systems dont have an inbox.  

Though inbox is an important app for most people.

So I can see the argument for putting in the LDP namespace and also for not doing that.  Perhaps ldp next will have some kind of extension namespaces.

In terms of implementations, this needs to be finalized hopefully quite quickly unless we have implementations support two predicates.

**Comment by nandana** [comment]
My slight preference would be not to use the LDP namespace. May be just for LDN this might work but I don't think this would most most suitable approach when more extensions start to appear. 

+1 for LDP Next to have a extension namespace.

**Comment by timbl** [comment]
"+1 for LDP Next to have a extension namespace." What do you mean by that?  A different URI for new terms for people to add things?  That to me seems less than ideal. It was a bad idea to make rdf: different from rdfs: I think in retrospect.   It was confusing to make dc: and dct: different.   I think the community is served better by putting new terms in the old namespace.  I thing this term should either go in ldp: or in solid-terms.   LDP makes sense if there may all kinds of application areas which use it as a basic way of hanging a handler of a file (like inotify in a file system http://man7.org/linux/man-pages/man7/inotify.7.html)?

**Comment by csarven** [comment]
Crosslinking to get LDP Next CG's feedback: https://lists.w3.org/Archives/Public/public-ldpnext/2016Aug/0001.html

**Comment by azaroth42** [comment]
I'm strongly -1 to using an existing namespace without due process.  I can't just create new entries in foaf, dcterms, html, or any other namespace ... and I don't see why ldp's namespace is any different and would formally object on this basis.

**Comment by sandhawke** [comment]
@azaroth42 This is due process.   W3C groups (and submissions) can write to W3C namespaces, assuming their decisions are made with appropriate public input.    The LDN FPWD highlighted the issue ( https://www.w3.org/TR/ldn/#issue-13 ), and @csarven is currently trying to make sure people who might care about this have a chance to weigh in before the relevant Working Group makes its decision.

Does that address your concern?

**Comment by akuckartz** [comment]
:+1: for using `ldp` namespace

**Comment by azaroth42** [comment]
I wish I had realized that! We would have taken over a bunch of namespaces in the Annotation Working Group and fixed them. Notably:  https://www.w3.org/TR/Content-in-RDF10/ which we used in the community group's work and then had to change as it's only a WD. And updated PROV so that we could have used it rather than reducing down to dcterms. Bummer.

Last modification wins, regardless of what's in a group's charter, seems inexcusably dangerous to me, but if that's sufficient process, so be it. I look forwards to adding textDirection and processingLanguage retroactively to the ActivityStreams namespace :wink:

**Comment by sandhawke** [comment]
I'm sorry if you've gotten conflicting messages, @azaroth42.   The W3C Staff owes you a consistent policy here.   I've raised the issue internally, and hopefully we'll have our stories better aligned in short order.

**Comment by csarven** [comment]
If the W3C gig thing doesn't work out, we can consider the following possibilities to have the **single property** (_inbox_) that the spec needs:

https://w3id.org/ldn
http://schema.org/

or alternatives:

http://www.w3.org/ns/ldn
http://ietf.org/ldn
http://microformats.org/ns/ldn
urn:LDN
magnet:?xt=urn:btih:071ab45e149b9124137902f3b97831468a94774c&dn=ldn.ttl...
http://doi.org/ldn
http://test@csarven.ca:1234/vocab-dept/v0.5/78/linkedData-NOTIFICATIONS.rdf

**Comment by sandhawke** [comment]
Don't forget tag: URIs.   :-)

**Comment by csarven** [comment]
Something along the lines of below is what's requested to be added to the LDP ns:

``` turtle
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix dcterms: <http://purl.org/dc/terms/>.
@prefix vs: <http://www.w3.org/2003/06/sw-vocab-status/ns#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix : <http://www.w3.org/ns/ldp#>.

:inbox
    a rdf:Property;
    rdfs:comment "Links a resource to a container where the notifications can be created and discovered.";
    vs:term_status "stable";
    rdfs:isDefinedBy <https://www.w3.org/TR/ldn/>;
    rdfs:label "inbox";
    dcterms:issued "2016-09-13"^^xsd:date;
    dcterms:creator <http://csarven.ca/#i>, <https://rhiaro.co.uk/#me>.
```

(Update: removed domain/range rdfs:Resource)

**Comment by akuckartz** [comment]
@csarven Aren't these two lines redundant?

```
    rdfs:domain rdfs:Resource;
    rdfs:range rdfs:Resource;
```

**Comment by csarven** [comment]
@akuckartz Yes, normally. It follows the LDP vocabulary as close as possible so that if/when it gets added it is uniform with the rest of the definitions. Copy/paste eventually.

**Comment by timbl** [comment]
Agree with @akuckartz .   Any statements of the form 

```
   rdfs:domain rdfs:Resource;
    rdfs:range rdfs:Resource;
```

have no information content.  They are tautological. Putting them in is bad practice - they should be removed.

**Comment by csarven** [comment]
I literally copy/pasted parts from the current `curl -H"Accept: text/turtle" http://www.w3.org/ns/ldp`, and added new information for ldp:inbox so if any consistency/right/wrong is desired to maintain uniformity after the addition, it is there. I agree that rdfs:Resource is unnecessary. Okay to remove it.

The spec says that any resource can have an Inbox. We implicitly mean rdfs:Resource/owl:Thing, but more importantly a IRI (HTTP URI to be specific).

**Comment by kidehen** [comment]
@csarven, methinks:

{
@prefix rdfs: `<http://www.w3.org/2000/01/rdf-schema#>`.
@prefix rdf: `<http://www.w3.org/1999/02/22-rdf-syntax-ns#>`.
@prefix dcterms: `<http://purl.org/dc/terms/>`.
@prefix vs: `<http://www.w3.org/2003/06/sw-vocab-status/ns#>` .
@prefix xsd: `<http://www.w3.org/2001/XMLSchema#>`.
@prefix : `<http://www.w3.org/ns/ldp#>`.

`:inbox`
    a rdf:Property;
    rdfs:comment "Links a resource to its Inbox (container) where the notifications can be discovered.";
    vs:term_status "stable";
    rdfs:isDefinedBy `<https://www.w3.org/TR/ldn/>` ;
    rdfs:label "inbox";
    dcterms:issued "2016-09-13"^^xsd:date;
    dcterms:creator `<http://csarven.ca/#i>`, `<https://rhiaro.co.uk/#me>`;

  # Plus 
  # This relations associates People, Organizations, and Documents with an inbox-folder 
  # (and LDP container or WebDAV collection)

   schema:domainIncludes schema:CreativeWork, foaf:Document, schema:Person, schema:Organization, foaf:Organization;
   schema:rangeIncludes ldp:Container. 
}

The definition above will work fine with regards to anything we have, on the Virtuoso and/or Virtuoso+ODS fronts.

If you have an problem with namespaces, just park the new relation definition here:

{
@prefix rdfs: `<http://www.w3.org/2000/01/rdf-schema#>`.
@prefix rdf: `<http://www.w3.org/1999/02/22-rdf-syntax-ns#>`.
@prefix dcterms: `<http://purl.org/dc/terms/>`.
@prefix vs: `<http://www.w3.org/2003/06/sw-vocab-status/ns#>` .
@prefix xsd: `<http://www.w3.org/2001/XMLSchema#>`.
@prefix : `<http://www.w3.org/ns/ldp#>`.

<#inbox>
    a rdf:Property;
    rdfs:comment "Links a resource to its Inbox (container) where the notifications can be discovered.";
    vs:term_status "stable";
    rdfs:isDefinedBy `<#>` ;
    rdfs:label "inbox";
    dcterms:issued "2016-09-13"^^xsd:date;
    dcterms:creator `<http://csarven.ca/#i>`, `<https://rhiaro.co.uk/#me>`;

   # Plus 
   # This relations associates People, Organizations, and Documents with an inbox-folder 
   # (and LDP container or WebDAV collection)

   schema:domainIncludes schema:CreativeWork, foaf:Document, schema:Person, schema:Organization, foaf:Organization;
   schema:rangeIncludes ldp:Container ;
  schema:mainEntityOfPage `<https://www.pinterest.com/pin/389561436502292321/>` . 
}

**Comment by rhiaro** [comment]
We discussed this at the breakout session at TPAC, which had lots of LDP people in the room, and there were no objections to the specific proposal to add `inbox` to the LDP namespace.

W3C policy on this is still being decided though.

Question: If there are no objections from community and no W3C legal issues, can we proceed with this without a longer term W3C process?

**Comment by azaroth42** [comment]
I'll moderate my -1 to -0.  I think it sets a bad precedent for groups to be changing each others' specifications, but as there's currently no process, I'll keep my discussion to that thread.  I have no objections to this specific addition, other than that no one will know what inbox means as it's not part of the LDP TR.

**Comment by rhiaro** [comment]
I agree process is preferable. But I don't want to get stuck.

> no one will know what inbox means as it's not part of the LDP TR

In the namespace we will include a link to the spec that _does_ define it, so people won't know what it means only if they fail to read that. If they're looking at the ns they have to try really hard not to see it.

**Comment by azaroth42** [comment]
Sorry, missed the `rdfs:isDefinedBy` link. Still -0, but that should cover it.

**Comment by kidehen** [comment]
@csarven note my update to  https://github.com/csarven/ldn/issues/13#issuecomment-248368979 which includes: 
- a schema:mainEntityOfPage relation that has object: https://www.pinterest.com/pin/389561436502292321/ 
- rdfs:isDefinedBy relation object correction to reflect use of Github as the namespace for now. 

Methinks, actually having a resolvable description of a relation that's machine- and human-comprehensible is more important than its namespace i.e., W3C namespace grounding doesn't guarantee relation comprehension or adoption which are the most important factors here :)

**Comment by nandana** [comment]
After the TPAC discussions, I am +1 for using the LDP namespace.  With rdfs:isDefinedBy, dcterms:issued, dcterms:creator properties, I guess it is clear that the term was added later and where it was defined.

The only other concern I had was that a developer looking at the namespace document might come to the conclusion that a generic LDP client/server should understand the semantics of the "inbox" property (which is not the case, right?). However, currently the namespace doc seems to have enough information to tell that it is coming from a separate spec.

**Comment by csarven** [comment]
Proposal to add to the JSON-LD context ( http://www.w3.org/ns/ldp.jsonld ):

``` json
"inbox": {"@id": "ldp:inbox", "@type":"@id"}
```

**Comment by danbri** [comment]
+1 for adding it to LDP. If you hit obstacles, give me a shout and we could look at whether schema.org might work instead. But LDP seems a natural home for it...

**Comment by rhiaro** [comment]
Following discussion on this thread, mailing list outreach, in-person at TPAC, and internal at W3C, it seems like adding `inbox` to the [LDP namespace](http://www.w3.org/ns/ldp/) is probably fine, so I've done so, with the disclaimer that if LDN doesn't make it to rec in the end it'll be removed.
