### ISSUE TITLE
Updates to notifications

### ISSUE THREAD

**Issue by csarven** [csarven/ldn#14]
Should the spec include how to update notifications e.g., delete, update? Out of scope? Depends on data model?

**Comment by rhiaro** [comment]
'just' LDP changing resources?

**Comment by csarven** [comment]
Mostly but not necessarily in LDP terms. General instructions and expectations for operations that are closely aligned with HTTP DELETE, PUT, PATCH.

One use-case:
1. User makes an annotation (stores it on their server) and sends a notification to the receiver.
2. User decides to delete their annotation.

What should happen next? User sends a new notification to the receiver that they deleted something (in that case it is a new notification about another notification and what to do for it) or delete the notification itself (in that case, do they have access to do so?)

Considerations with the data model: for example: AS2 will announce different activities for something was Created, Deleted, or Undone - like a log. In other models, this may not be desired i.e., the user just wants to delete/undo the earlier notification.

If at all, how much should this spec describe this - perhaps non-normative? Aside: I'm feeling that we might need a section on 'Common Application Stuff'

**Comment by rhiaro** [comment]
I think this is totally out of scope. Social (or other) applications that send notifications in different ways can all use the LDN mechanism. AP does it a certain way with AS2, another protocol might make different decisions about when to send notifications... And once a notification has been created on a server, it is a web resource like any other. If that server has some way of doing write operations on its resources (like LDP) that's fine. If not, also fine. We can probably leave this out altogether.

**Comment by csarven** [comment]
Okay to leave it out. Whether HTTP methods are used, or the server physically updates (out of band), or by another approach is fine. The focus of the spec is about discovery/delivery/reuse as opposed to management or updates.
