### ISSUE TITLE
Inbox and notification persistence, permanence, integrity

### ISSUE THREAD

**Issue by csarven** [csarven/ldn#17]
This was originally a stub in the spec but removed when we started to work on it. Recently @BigBlueHat raised the following:

> The examples show non identified (no id/@id) graphs hitting the inbox (which is fine), and the inbox assigning an id to it (which is also fine).
> 
> What is the expectation for these IRI's long term? Is the inbox expected to grow infinitely? Do they get moved off and renamed when "processed"?
> 
> I don't have a good answer for it yet...
> 
> Web Mention, Web Hooks, and http://www.relify.com/ (the LINK method returns!) all have these ephemeral things that disappear after transport (or at least are likely to). They effect things on the receiving end, but don't themselves have identification.
> 
> Email on the other hand has Message-ID and those (as we all know well) stick around long term and may or (sadly) may not be processed into better locations.

How do we go from here? Is this part of the spec? Non-normative?

Also, we only discuss POST in the spec, PUT can be added as well.

**Comment by BigBlueHat** [comment]
You might have a look then at what the Web Annotation Working Group did with `canonical` and `via` in the [Web Annotation Data Model](http://w3c.github.io/web-annotation/model/wd2/#h-other-identities)
and the third paragraph or so in this section of the [Web Annotation Protocol](http://w3c.github.io/web-annotation/protocol/wd/#h-create-a-new-annotation) doc:

> If the Annotation contains a canonical link, then it MUST be maintained without change. If the Annotation has an IRI in the id property, then it SHOULD be copied to the via property, and the IRI assigned by the server, at which the Annotation will be available, MUST be put in the id field to replace it.

That would then allow the originator of the message to provide an identity before sending the notification, for the message to get a new identity upon receipt, and for the message to even be passed along to other inboxes (relayed) with the `via` chain of identities accumulated along the way (similar to [RFC822’s `Reference` header](http://tools.ietf.org/html/rfc822#section-4.6.3)).

TimBL apparently got to all this first (shock!)…from 1992:
https://www.w3.org/Protocols/HTTP/Object_Headers.html#uri
https://www.w3.org/Protocols/HTTP/Object_Headers.html#message-id
…and likely many other places...

Lastly, the `via` in the Web Annotation Data Model spec should not be confused with the [`Via` HTTP header](https://tools.ietf.org/html/rfc7230#section-5.7.1) which is about proxy “paths” not naming history.

This one’s ours: http://w3c.github.io/web-annotation/vocab/wd/#via
We cribbed the name from Atom’s `via` link relationship value: http://tools.ietf.org/html/rfc4287

**Comment by BigBlueHat** [comment]
Also, I'd avoid PUT. This needs to be providing something not already in place within LDP.

A simple way to discover, POST, and wander off is great! Anything else (listing, etc) can probably be left to other specs (LDP's various containers in this case).

**Comment by rhiaro** [comment]
Some of the updates that have been made since this was opened, in particular to line up with ActivityPub, mean I think this is covered.

> allow the originator of the message to provide an identity before sending the notification, 

If you post objects with `@id` set, they are preserved. You can use this for the notification itself (as in AP) or any other resources you're including.

> for the message to get a new identity upon receipt, 

If you post objects with `@id` relative (`""`) or missing then the new URI generated can be inferred to identify these objects.

> and for the message to even be passed along to other inboxes (relayed) with the via chain of identities accumulated along the way

A receiver can forward any incoming notifications, and add new properties to them (like `via`), but mentioning this is out of scope of the spec.

**Comment by BigBlueHat** [comment]
Overall I'm :+1: for all these. :smile: 

One question, though, regarding this statement:

> You can use this for the notification itself (as in AP) or any other resources you're including.

Does that mean, I could send this annotation https://www.w3.org/TR/annotation-model/#example to an inbox and it would preserve All The Things?

Does that then mean that the notification itself does not get an `@id` (as originally proposed) unless one was not previously provided?

**Comment by csarven** [comment]
The notification content is kept as is. The `@id` value is treated as per JSON-LD parsing rules. If the value is an URI, that gets used as the node identifier (subject). If the value is empty, it is resolved against the document base.

The relation (`ldp:contains`) on the Inbox URL points at the notification URI (what's deferenceable in the end), not the `@id` value. It may be that the notification URI (what was created by the server) and the `@id` end up being the same if the sender leaves `@id` empty. Same as using `<>` in Turtle so that it eventually resolves against the base URI.

If the annotation example is POSTed to `http://example.org/inbox/` with the following

```
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/anno1",
  "type": "Annotation",
  "body": "http://example.org/post1",
  "target": "http://example.com/page1"
}
```

and the server responds with `Location: http://example.org/inbox/foo`, and creates:

```
<http://example.org/inbox/> ldp:contains <http://example.org/inbox/foo> .
```

where `http://example.org/inbox/foo` returns the exact payload that was originally POSTed, including `"id": "http://example.org/anno1"`.

**Comment by BigBlueHat** [comment]
Gotcha. So if I were to then dereference `http://example.org/inbox/foo` (in the example above), I'd get the example annotation verbatim?

That would then mean that the `Request-URI` and the `@id` do not match.

I don't suppose that's a problem technically, but it may be prudent to note that somewhere or other to avoid confusion by consuming clients--as they'll likely then need to store both those identifiers (at least if they want to re-retrieve a copy from the inbox and/or compare that to any graph found by dereferencing the value of `@id`).

**Comment by csarven** [comment]
Right. The `Request-URI` and the `@id` do not necessarily match. This is no different than any off the shelf RDF publishing. Added a note here: https://github.com/csarven/ldn/commit/db291e92535427cbf34046fa2bc0faf7e4457d00 . How does that sound?

**Comment by BigBlueHat** [comment]
:+1: :shipit:

**Comment by csarven** [comment]
:ship:d
