### ISSUE TITLE
URI for notification

### ISSUE THREAD

**Issue by rhiaro** [csarven/ldn#19]
Do we need to say anything about the receiver being responsible for generating a URI for a notification sent to the inbox? LDP says:

> 5.2.3.7 LDP servers creating a LDP-RS via POST MUST interpret the null relative URI for the subject of triples in the LDP-RS representation in the request entity body as identifying the entity in the request body. Commonly, that entity is the model for the "to be created" LDPR, so triples whose subject is the null relative URI result in triples in the created resource whose subject is the created resource.
> 
> 5.2.3.8 LDP servers SHOULD assign the URI for the resource to be created using server application specific rules in the absence of a client hint.
> 
> 5.2.3.9 LDP servers SHOULD allow clients to create new resources without requiring detailed knowledge of application-specific constraints. This is a consequence of the requirement to enable simple creation and modification of LDPRs. LDP servers expose these application-specific constraints as described in section 4.2.1 General.
> 
> 5.2.3.10 LDP servers MAY allow clients to suggest the URI for a resource created through POST, using the HTTP Slug header as defined in [RFC5023]. LDP adds no new requirements to this usage, so its presence functions as a client hint to the server providing a desired string to be incorporated into the server's final choice of resource URI.

We could perhaps say this more succinctly.

**Comment by csarven** [comment]
See also https://github.com/csarven/ldn/issues/17

**Comment by csarven** [comment]
Covered through commits in issue #22
