### ISSUE TITLE
consumer / receiver difference ?

### ISSUE THREAD

**Issue by akuckartz** [csarven/ldn#2]
Please clarify the difference between consumers and receivers.

**Comment by rhiaro** [comment]
The receiver is basically the server that has the notifications POSTed to it, whether you think of this like creating resources inside an LDP container, or an endpoint with a script that processes these requests and stores them somewhere. The receiver is also responsible for exposing the POSTed notifications for retreival by other applications.

These other applications are the _consumers_. They need to know 1. how to discover an Inbox from a resource (such as an article or user profile) and 2. how to fetch the contents of the Inbox, eg. to display it nicely for a human.

They can be implemented completely independently, and we anticipate consumers to be specialised and able to read certain types (vocabularies) of notifications from an Inbox for a particular purpose, not necessarily everything all the time.

Does that help? Is there a specific part of the spec right now where you think this is confusing and could be worded better?

**Comment by csarven** [comment]
I think this is sufficiently addressed in the spec at this point. If there is a particular wording that's unclear or can be improved, lets focus on that. Issue #21 also touched on this recently.
