### ISSUE TITLE
Notifications?  Or queuing mechanism?

### ISSUE THREAD

**Issue by gklyne** [csarven/ldn#21]
On a quick scan of the spec, I'm not seeing any way for consumers too receive notifications asynchronously which, in my perspective, would be the whole point of "notification"s.

What I do see is a queueing mechanism that allows one party to queue information packets, and another to retrieve them when they're ready.

Maybe this is fine and useful, but if so I guess I'd suggest the spec may be misnamed.

**Comment by csarven** [comment]
Are you looking for a way the sender and the consumer can communicate directly? The spec does have the condition that the receiver stores the notification as an intermediary. The notifications in this case are not ephemeral but resources with their own URIs.

**Comment by gklyne** [comment]
Not necessarily direct communication. I'm quite comfortable with the idea that a notification is a distinct resource with its own URI.

As I read the current spec, the consumer is required to poll (GET) to see if a notification is available.  I'm not seeing any way that the consumer can be notified (sic) without such polling (e.g. by subscribing a URI to be prodded when a new notification becomes available).

(I could understand that such a mechanism is out of scope for the design/requirements you have in mind - but, from my experience, that's what I expect "notification" to mean.)

**Comment by csarven** [comment]
The spec doesn't prevent consumers and receivers from communicating in real-time but doesn't describe how right now. This is possibly out of scope, but which of the various real-time communication mechanisms would you implement?

**Comment by gklyne** [comment]
I'd probably go for something like the consumer offering a URI that the receiver can post to when a notification arrives.  E.g. something along the lines of http://www.w3.org/TR/prov-aq/#provenance-pingback.  But that's just a possible mechanism, and the specifics aren't so important (though preferably incrementally easy to implement within the context of an LDP stack).

**Comment by csarven** [comment]
In your scenario, it sounds like the consumer is also a receiver, and the receiver is also a sender.

What we don't have is a way for any receivers to _request_ things from senders. This is a subscription mechanism, and there are several existing options. I think it's out of scope for LDN to add anything new, but it certainly doesn't prevent people from implementing the subscription mechanism they prefer in receivers and senders.

Having said that, we're open to proposals for subscription mechanisms which you 1) prefer and why 2) have implemented or plan to implement before the end of Candidate Recommendation. If there's consensus around something like this, it's possible we can recommend one for use with LDN in particular.

It's also worth noting that other specs in the SocialWG include subscription mechanisms: ActivityPub and PubSubHubbub.

**Comment by stain** [comment]
Agree on a "ping" mechanism like PROV ping, possibly where you register to be ping with a kind of "You have new mail" (but not what) - that way you don't need to ping for every notification and can rate-limit.

**Comment by melvincarvalho** [comment]
> Issues should only be closed with apparent consensus of the participants. If consensus cannot be reached, it is elevated to a WG telecon, and then closed with consensus of the Working Group. 

https://www.w3.org/wiki/Socialwg/Github_Process

Only a few minutes passed before your response and closing the issue.  IMHO that could not have been enough time to allow consensus of the participants to be reached.

In any case, thanks for reopening.  And allowing constructive suggestions.

**Comment by melvincarvalho** [comment]
Apologies, wrong thread [ DELETED ]

**Comment by mklyne** [comment]
Per your terminology, it may well be that what I'm suggesting is a consumer that performs technical interactions similar to a receiver.  But I'm not sure that's of itself useful focus. (I found the terms "consumer" and "receiver" a bit arbitrary, but, hey, you gotta call them something.)

My understanding was that the "consumer" is a component that is a final recipient of a notification, and a "receiver" is a hub-like component that provides a common point of contact between originator and consumer.

My suggestion (or expectation) was that the pubsub-style of interaction be propagated all the way to the consumer, so that a consumer that is able to maintain a listening point is not forced to poll.

If your intent is that other Solid mechanisms be used to provide this kind of capability, then I think it could help to explain this in the spec:  the name "notification" raises (for me) the expectation that it can be delivered asynchronously (i.e. non-polled).

**Comment by gklyne** [comment]
Oops... that last comment was me, accidentally posted using wrong Github account.

**Comment by csarven** [comment]
Right. In terms of who gets to store and view the notification, it is the receiver and the consumer respectively. I agree that one way of looking at notifications is _stuff that comes to me_. We are just more explicit about who that is by splitting them up: one that stores the notification, and the one that makes a request to view it. If a notification can be accessed but a consumer doesn't request it, is it not a notification? _If a tree falls in a forest..._

I acknowledge the usefulness of a subscription mechanism, but 1) it is slightly out of LDN's scope and 2) there are existing approaches out there we can point to - without mandating a single one for conformance. Perhaps the middle ground is:

_Proposal_: To improve the spec, add **an informative section** (maybe an Appendix?) about some possible ways to do a subscription mechanism as well as pointers to relevant specs.

How does that sound?

**Comment by gklyne** [comment]
If async notification is out of scope for LDN, then I think it would be good for this to be clear right up front, preferably in the abstract, so that people like me looking for such a mechanism don't have to read the whole spec.

As for adding an informative section as you suggest - I'm easy about that, but I'm not sure if it would be worth the effort.

**Comment by akuckartz** [comment]
Such an informative can potentially be the foundation for more.

**Comment by akuckartz** [comment]
That should have been "informative section".

(The mobile GitHub interface does not allow editing comments after they have been submitted :-(

**Comment by gklyne** [comment]
(re informative section...) Indeed, but if you're aiming this for some kind of standards track then it also becomes something else for people to disagree about.  If async notifications is out of scope for this, then say so, and leave discussion of options to a separate document.  My 2c.

**Comment by csarven** [comment]
Added an initial non-normative section: https://linkedresearch.org/ldn/#subscribing-to-notifications . Is something like that acceptable for this issue?

**Comment by gklyne** [comment]
I think the informative section is fine.

But...

Now I find myself asking:  what is it about a "notification" that distinguishes it from an arbitrary message.  I just skimmed every occurrence of "notification" and mentally replaced it with "message", and I don't think it makes any fundamental difference to the spec.  Why are you calling them "notifications"?

Related, I think the abstract could be a little more informative about the intended scope of use of this protocol. E.g.

> Linked Data Notifications is a protocol to facilitate exchanging notification messages between applications which serve as senders, receivers and/or consumers of RDF data.  Notification messages are intended to be used to provide information about resources managed using LDP protocols, such as status changes or other events related to the resource.  The protocol described here is entirely synchronous, and does not provide for asynchronous delivery of notification messages.

This is just an example of what _**I**_ think you're intending to specify here.  My point here is to be more explicit so that it is easier for someone to figure out if the protocol might be relevant to something they are trying to do with linked data.

**Comment by csarven** [comment]
Updated the Abstract. What do you think?

We tried to emphasise that the receiver is the focal point with regard to receipt of notifications. Technically the _receiver_ can have notifications delivered to it asynchronously. The consumer is an additional piece, so that notifications can be reused.

> information about resources managed using LDP protocols

This isn't true - notifications can be about any resources, regardless of how they are managed.

**Comment by gklyne** [comment]
I think that's more informative.

(I hadn't grasped the bit about the main focus being on receivers, and consumers being "extras".)
