### ISSUE TITLE
explain relationship to webmention

### ISSUE THREAD

**Issue by dret** [csarven/ldn#25]
i am sure that the LDP WG is aware of webmention, an #HTML5 protocol under development to satisfy a very similar set of use cases http://webconcepts.info/specs/W3C/TR/webmention. since both specs are under development by the same organization, it would be useful if LDN explained its relationship to webmention, and why it is inventing a new protocol.

**Comment by melvincarvalho** [comment]
LDN is a well specified super set of webmention that is interoperable with with existing W3C standards such as linked data.  

Webmention does not interoperate (with anything other than itself).  I have suggested that the webmention message format (which is restricted to form encoded variables) should create a mapping to linked data, e.g. in JSON, in order to increase the network effect.  Vocal members of the webmention community are against implementing JSON, however.  

LDN is a spec because it takes forward many of the use cases that the WG is trying to solve.  As it happens that includes the messaging element of webmention use case.  But it stands on it's own merits, I am unsure why there needs to be such an explanation.

**Comment by dret** [comment]
On Jul 26, 2016, at 09:23, Melvin Carvalho notifications@github.com wrote:

> LDN is a well specified super set of webmention that is interoperable with with existing W3C standards such as linked data.

if it indeed is a superset, then the spec should mention that and maybe there even is so common interop ground to be found?

> LDN is a spec because it takes forward many of the use cases that the WG is trying to solve. As it happens that includes the messaging element of webmention use case. But it stands on it's own merits, I am unsure why there needs to be such an explanation.

it makes it easier for people to understand the spec ecosystem and tje relationships between specs. in the end, maybe there's a simple answer to the question of "why are there two notification protocols under development at @w3c"? if there is, it would be helpful to include that as a non-normative part, instead of telling developers to figure it out themselves.

to me, putting a spec in context is good spec writing practice, but it's mostly a "be friendly to developers" question.

**Comment by rhiaro** [comment]
LDN and Webmention are compared in Social Web Protocols: http://w3c-social.github.io/social-web-protocols/#delivery (Not finished yet, ongoing). 

SWP will also contain specific instructions on how to bridge between them.

LDN doesn't assume that the source of the notification links to / contains the URL string of the target, so a broader scope of data can be sent as the notification payload. This is similar to the mechanism used by the delivery part of ActivityPub (a whole AS2 Activity is sent, with authentication headers), so we're working on syncing up there so we don't duplicate work there.

**Comment by melvincarvalho** [comment]
@dret 

> why are there two notification protocols under development at @w3c"

I've been asking myself the same question!  I would much prefer one.

**Comment by csarven** [comment]
@dret Webmention and LDN do indeed share similar use cases, however, there are sufficient differences/interests.

Some of the differences are that, LDN ensures that the notification gets its own URL, whereas in Webmention it is ephemeral.

LDN specifies how to find and consume notifications, as well as sending. The notification can have any content. In Webmention, the most one can derive is that "A hyperlinks to B" (the least being that "A includes string B"), after verification. The exact relation is unknown - essentially at the discretion of each receiving implementation if/how they want to figure that out. In LDN, the notification can be of different types: not only can the message indicate that "A has a specific set of relations to B", but it can also say "Such and such happened".

**Comment by dret** [comment]
On 2016-07-26 11:35, Sarven Capadisli wrote:

> @dret https://github.com/dret Webmention and LDN do indeed share
> similar use cases, however, there are sufficient differences/interests.
> 
> Some of the differences are that, LDN ensures that the notification gets
> its own URL, whereas in Webmention it is ephemeral.
> LDN specifies how to find and consume notifications, as well as sending.
> The notification can have any content. In Webmention, the most one can
> derive is that "A hyperlinks to B" (the least being that "A includes
> string B"), after verification. The exact relation is unknown -
> essentially at the discretion of each receiving implementation if/how
> they want to figure that out. In LDN, the notification can be of
> different types: not only can the message indicate that "A has a
> specific set of relations to B", but it can also say "Such and such
> happened".

i think something along these lines would be great to have in some short 
and informal spec appendix. in the end, you will have developers looking 
at both specs and wondering "how do they differ, which one should i 
choose"? pointing them at the big differences in the way that you have 
done in this one paragraph would be very helpful for them.

**Comment by csarven** [comment]
@dret Thanks for the feedback. If I may say so, the general consensus in the WG is that, we shift this sort of information over to the _Social Web Protocols_. It also has an opportunity to get into even more detail e.g., use this protocol when you want to do x,y,z. SWP is mentioned and linked to in LDN's introduction: https://www.w3.org/TR/ldn/#social-web-working-group and the other specs that are being produced by the Social Web WG are following this pattern or intend to. I hope this addresses your concern for this issue.

**Comment by akuckartz** [comment]
@dret The long discussion in this webmention issue probably is the best answer to your initial question: https://github.com/w3c/webmention/issues/51

**Comment by dret** [comment]
On 2016-07-26 17:42, Sarven Capadisli wrote:

> @dret https://github.com/dret Thanks for the feedback. If I may say
> so, the general consensus in the WG is that, we shift this sort of
> information over to the /Social Web Protocols/. It also has an
> opportunity to get into even more detail e.g., use this protocol when
> you want to do x,y,z. SWP is mentioned and linked to in LDN's
> introduction: https://www.w3.org/TR/ldn/#social-web-working-group and
> the other specs that are being produced by the Social Web WG are
> following this pattern or intend to. I hope this addresses your concern
> for this issue.

sounds good enough. my concern mostly is the sprawling ecosystem of 
various camps with various preferences defining various formats and 
protocols. and to some extent that's natural and fine, and nature will 
take its course. it's just that out of courtesy for the poor developers 
trying to follow that sprawling ecosystem, it is nice to put things in 
perspective at least a little bit, so that they can better figure out 
how and why those variations came into being.

from what you're saying it seems that you are planning on documenting 
this. this is great and very helpful. thanks a lot, and i'll go forward 
and close this issue.
