### ISSUE TITLE
Consider adding a section for Web IDL

### ISSUE THREAD

**Issue by csarven** [csarven/ldn#3]
Raised by @rtroncy

**Comment by sandhawke** [comment]
I'd think it's best to leave that that until some point in the future when it's being implemented by browsers.   I think we're a long way from that.   For now, there's no need to standardize a library interface like that.   There can be lots of implementations, in lots of different languages, all with different APIs.  Eventually, maybe there will be a JS API that's clearly dominant, and there might be reason to implement in browsers, but at this point, it seems quite premature.

**Comment by akuckartz** [comment]
:-1: I agree with @sandhawke
