### ISSUE TITLE
GET requests on receivers with no Accept header

### ISSUE THREAD

**Issue by acoburn** [csarven/ldn#31]
In the context of receivers making an inbox accessible to consumers, the draft LDN specification states in [section 3.4.2](https://www.w3.org/TR/2016/WD-ldn-20160726/#receiving-inbox-contents) that:

> If the GET request has no Accept header, the results must be returned as JSON-LD; otherwise the receiver should return the results in the serialization requested, or a 415 Unsupported Media Type error if the requested serialization is not available.

I was planning to use an LDP server implementation as an LDN receiver, but the LDP specification (i.e. [section 4.3.2.2](https://www.w3.org/TR/ldp/#ldprs-get-conneg)) states that:

> LDP servers should respond with a text/turtle representation of the requested LDP-RS whenever the Accept request header is absent

So in the case where the GET request has no Accept header, these two specs are pointing to different serializations. Would it be possible to get some clarification about that difference?

**Comment by csarven** [comment]
@acoburn Good catch! Thank you for raising this.

I think LDN should stick close to expected LDP behaviour.

How about the following: https://github.com/csarven/ldn/commit/95eb604b5d10642c970e2bbbd6f8124936fc6501 .

Consumers SHOULD use an Accept header. If the Accept header is not specified, the behaviour is default [RFC 7231 Accept](https://tools.ietf.org/html/rfc7231#section-5.3.2):

> A request without any Accept header field implies that the user agent will accept any media type in response.

and receivers SHOULD return JSON-LD or Turtle in absence of the Accept header.

This should keep existing LDP implementations (receivers) happy.

What do you think?

**Comment by acoburn** [comment]
@csarven your change looks great. Thanks!
