### ISSUE TITLE
Backoff strategy for discovery

### ISSUE THREAD

**Issue by rhiaro** [csarven/ldn#32]
Similar to https://github.com/w3c/webmention/issues/48, how many times should a Sender/Consumer that wants to do discovery several times on one resource, or multiple target resources on the same domain, try to find the inbox endpoint before it gives up? To avoid knocking over a server, or being blocked for too many GET requests?

**Comment by rhiaro** [comment]
Update: webmention is resolving this by adding something or replacing the User-Agent value (if present) but I think this is not possible or very complicated for JS implementations, so not a good recommendation for LDN

**Comment by akuckartz** [comment]
I suppose that guidelines regarding such http-questions exist somewhere.

**Comment by csarven** [comment]
Added a non-normative sub-section "Retry Discovery" under Considerations: https://github.com/csarven/ldn/commit/da56c9afeecbd5d34b9b20ff663981aa4017fb74

**Comment by rhiaro** [comment]
F2F resolution was to add note to SWP (or external Note) about not accidentally beating servers up with discovery. Unless @bigbluehat finds an existing note about it first.

https://github.com/w3c-social/social-web-protocols/issues/38

**Comment by rhiaro** [comment]
Decision: Put a specific link in Discovery section linking to section in SWP.

**Comment by aaronpk** [comment]
What does "courteous" mean? Also this fragment ID referenced in 2bf7c0bac82712e203b8a0032c1d8a1a05640490 doesn't seem to exist https://www.w3.org/TR/social-web-protocols/#targeting-and-discovery

**Comment by BigBlueHat** [comment]
Perhaps recommending something quantifiable like [Exponential Backoff](https://en.wikipedia.org/wiki/Exponential_backoff) would be best. There are lots of libraries for most common programming languages that do that--even for HTTP APIs.

**Comment by rhiaro** [comment]
Sorry about the broken SWP fragment, it's pre-empting a new WD: http://w3c-social.github.io/social-web-protocols/#targeting-and-discovery
