### ISSUE TITLE
Clarify paging mechanism

### ISSUE THREAD

**Issue by dmitrizagidulin** [csarven/ldn#36]
Section 3.4.2 states (emphasis mine):

> "A successful GET request on the Inbox [...] MAY be subject to **paging** or access control restrictions at the receivers discretion"

If consumers may encounter paging, it may be helpful to mention the paging mechanism. Are we talking about [LDP Paging](https://www.w3.org/2012/ldp/hg/ldp-paging.html)? Something Hydra related?

**Comment by csarven** [comment]
Point taken. There is not a specific paging model that's overwhelmingly popular. Just to add to the mix, AS2 also offers different paging. We figured that the spec shouldn't enforce this at this point in time (hence "at the receivers discretion").

**Comment by csarven** [comment]
Per discussion: https://gitter.im/csarven/ldn?at=57e453a7df21a757301cf4dc moved paging under Considerations.

**Comment by dmitrizagidulin** [comment]
Thanks! That addresses my concern, closing.

**Comment by csarven** [comment]
F2F decided that we remove the Considerations section for Paging, and add an inline note along the lines of: This specification does not define a paging mechanism, here are some existing ones..
