### ISSUE TITLE
Create an overview diagram

### ISSUE THREAD

**Issue by csarven** [csarven/ldn#4]
Raised by @sandhawke

**Comment by csarven** [comment]
@sandhawke Is this required for the spec (as per W3C) or a nice to have / something you'd like to see? Are the other specs doing it; yes/no; why not? Any particular reason why LDN should?

I'm not opposed to having one. PRs are welcome. I'd like to know the boundaries and whether you are okay either way if this makes it into the spec or not (i.e., issue closing for whatever reason at any time).

**Comment by sandhawke** [comment]
Totally a would-be-nice-to-have.

Maybe as a sequence diagram...  http://stackoverflow.com/questions/1367059/tool-for-drawing-protocol-sequence-diagrams

Or something that shows the parties spread out in 2 dimensions instead of one.

**Comment by akuckartz** [comment]
:+1:

**Comment by csarven** [comment]
Created an overview diagram: https://github.com/csarven/ldn/blob/6ad955c8e1fe67846cea7fd8f51837cf6802208b/linked-data-notifications-overview.svg . Live on the Editor's Draft as well. Happy to improve on that. Does it sufficiently address this issue?

**Comment by sandhawke** [comment]
:+1:

**Comment by white-gecko** [comment]
Maybe it would be good, to distinguish between links/properties and requests, as I did in https://github.com/white-gecko/2016-08-29-LDN-Colloquium/blob/master/LingedDataNotifications/LDN-overview-all.svg
