### ISSUE TITLE
Editorial improvement

### ISSUE THREAD

**Issue by acka47** [csarven/ldn#45]
Re.

> The sender determines the target for a notification based on its own requirements; once determined, the sender discovers the location to send it to (the Inbox) from the target itself.

A lot of pronouns are used here which doesn't make this sentence easy to read:
- What does "its own" refer to? To "Sender" – which makes most sense? But it could also refer to "notification" or "target". Anyway, reference should be made unambiguous.
- "it" probably refers to "notification". Grammatically, "location" is the next word "it" might refer to . I would make this unambiguous.

**Comment by csarven** [comment]
Update to:

> The sender chooses a target resource to send notifications to; the sender then discovers the location of the target's Inbox.

Is that clear?

**Comment by csarven** [comment]
Revised to:

> The sender chooses a resource as the target for a notification. The sender then discovers the location of an <em>Inbox</em> from the target, and sends the notification there.

**Comment by acka47** [comment]
I like the first one – maybe with the addition from the second one:

> The sender chooses a target resource to send notifications to; the sender then discovers the location of the target's Inbox, and sends the notification there.

**Comment by csarven** [comment]
Sounds good. Lets go with that. Updated.
