### ISSUE TITLE
schema.org namespace

### ISSUE THREAD

**Issue by acoburn** [csarven/ldn#47]
Under [Section A](https://www.w3.org/TR/2016/WD-ldn-20160726/#document-conventions) of the draft spec, the `schema` prefix uses a namespace with a `https` scheme. Also, in the `index.html` [document](https://github.com/w3c/ldn/blob/master/index.html#L126), the `https` scheme is used, but in schema.org's documentation (and elsewhere in the LDN documentation) the plain `http` scheme is used. I believe that the plain `http` scheme is the correct one, i.e. `http://schema.org/`.

**Comment by csarven** [comment]
http and https are intended to be treated as equivalent in schema.org (sorry, I don't have a citation for this right at this minute.)

As of this writing, the latest Working Draft is https://www.w3.org/TR/2016/WD-ldn-20160926/ . The section on Document Conventions no longer exists - If I remember correctly, it was dropped two WD's ago. The current WD has an example where it uses the http. This is all non-normative in any case.

**Comment by acoburn** [comment]
@csarven thanks for the clarification.
