### ISSUE TITLE
Reference to expired IETF draft

### ISSUE THREAD

**Issue by r12a** [csarven/ldn#48]
sent on behalf of Felix Sasaki
https://www.w3.org/TR/ldn/

non i18n comment:  the draft refers to an IETF draft which has expired: https://tools.ietf.org/html/draft-wilde-accept-post-03 and seems not to be worked on. The WG should consider updating or dropping the reference.

**Comment by rhiaro** [comment]
Thanks @r12a and @fsasaki - The correct reference for Accept-Post is a section in the LDP spec. Updated this in https://github.com/w3c/ldn/commit/30ebb9f7af4cce4403e192057d0cd6542be1f9b4

**Comment by r12a** [comment]
satisfied, thanks
