### ISSUE TITLE
Example should have charset=UTF-8

### ISSUE THREAD

**Issue by r12a** [csarven/ldn#49]
[sent on behalf of Addison Phillips]
https://www.w3.org/TR/ldn/#discovery

Section 3.1 ("Discovery") contains an example of returning content type of text/html. This should include `charset=UTF-8` by way of setting a good example.

> Content-Type: text/html
> 
> &lt;a href="/inbox/" rel="http://www.w3.org/ns/ldp#inbox"&gt;My inbox&lt;/a&gt;

**Comment by csarven** [comment]
Added `charset=UTF-8` to all examples.

**Comment by csarven** [comment]
https://github.com/w3c/ldn/commit/556ab067a2ae5c938d91983cfe3b0cf0d1847e93 and https://github.com/w3c/ldn/commit/cef5421fb80ebd7e81532cf91ececa97aa56b7db

**Comment by csarven** [comment]
Removed extra space in ContenType and removed charset from JSON-LD examples
