### ISSUE TITLE
Examples in both Turtle and JSON-LD syntax

### ISSUE THREAD

**Issue by csarven** [csarven/ldn#5]
Raised by @sandhawke

**Comment by csarven** [comment]
Since we only require JSON-LD, better to keep the examples simple in the spec.

**Comment by akuckartz** [comment]
Turtle is simpler than JSON-LD. I therefore think that adding Turtle examples would improve the spec.

**Comment by csarven** [comment]
Added a Turtle example under discovery. The spec's baseline is JSON-LD, so we are only emphasising on that. I gave another pass at the examples with focus on different usage. I'd like the serialisation to be on the backdrop here. Folks coming into this spec will hopefully identify examples that resembles what they are after. We can't accommodate all use cases or serialisations. For now, JSON-LD, Turtle, and HTML+RDFa get some face time.
