### ISSUE TITLE
Add payload example using Webmention terms

### ISSUE THREAD

**Issue by aaronpk** [csarven/ldn#63]
Given that [Webmention](https://www.w3.org/TR/webmention/) is a W3C REC, and that LDN already has [an example](https://www.w3.org/TR/ldn/#payload-examples) of sending a Pingback payload, it seems appropriate to add an example using Webmention as well.

I think the Webmention example payload would look like the following, given the Webmention namespace document at https://www.w3.org/ns/webmention

```
{
  "@context": { "wm": "https://www.w3.org/ns/webmention" }
  "@id": "",
  "wm:source": { "@id": "http://example.net/reply" },
  "wm:target": { "@id": "http://example.org/article" }
}
```

**Comment by rhiaro** [comment]
I dunno, it seems unlikely that anyone looking at the LDN spec is going to straight up want to send webmentions as JSON. They might be looking if they want to *bridge* between LDN and Webmention, in which case this example is already in http://w3c-social.github.io/social-web-protocols/#ldn-to-wm

**Comment by csarven** [comment]
The Pingback example is not particularly interesting or useful either. Okay to remove that if need to.

There is a sufficient number and variety of examples in the spec in any case.

**Comment by melvincarvalho** [comment]
Commenting only on the syntax of the example.

Is this correct?

    "@id": "",

I think in this case you would want to have a [blank node](https://en.wikipedia.org/wiki/Blank_node) meaning a message that doesnt have a specific URI.  In this case you could leave out the @id completely:

```
{
  "@context": { "wm": "https://www.w3.org/ns/webmention" }
  "wm:source": { "@id": "http://example.net/reply" },
  "wm:target": { "@id": "http://example.org/article" }
}
```

OR to avoid a round trip of the context lookup
```
{
  "https://www.w3.org/ns/webmention#source": { "@id": "http://example.net/reply" },
  "https://www.w3.org/ns/webmention#target": { "@id": "http://example.org/article" }
}
```
Whether or not this example is included, I'd be interested to see the valid syntax on this, as it's something I raised before.  Let me know if you think that's correct. :)

**Comment by rhiaro** [comment]
@melvincarvalho if you want to debate the syntax of the examples in the spec, please open a new issue. For the record, either is correct, and both result in different semantics (no `@id` = blank node, empty `@id` = relative URI, run it through the JSON-LD playground if you're still not sure).

**Comment by melvincarvalho** [comment]
@rhiaro thank you for the clarification.  I am only looking at the syntax in the original post.  I also added a trailing # which you had in your example, and aaron did not have in OP.

**Comment by aaronpk** [comment]
Okay, the SWP already document covers this. It will be good to get an updated version of that published.
