### ISSUE TITLE
LDN to enable referencing of self-published articles

### ISSUE THREAD

**Issue by jibe-b** [csarven/ldn#65]
I am trying to see how LinkedData Notifications could be used within a process of content referencing and aggregation.

Let's consider an author (a scientist) who publishes a document online (scientific publication).
She does it using dokie.li and sends a LinkedData Notification to the Inbox of a content referencement and agregation website.

Then this website may use the metadata of the publication in any standard way, such as exposing it through a [OAI-PMH](https://www.openarchives.org/pmh/) or better [ResourceSync](http://www.openarchives.org/rs). Text-mining applications may then use such a referencing/agregator website (for example [Core](http://core.ac.uk/)) as en entry for getting papers to mine (see [OpenMinTeD](http://OpenMinTeD.eu) for example).

I do realize that this proxy website "recentralizes", somehow. But when it helps grasping loads of contents, let's say it helps.

**Comment by jibe-b** [comment]
May I ask for opinions about this?

This may already have been discussed and then I'd join the discussion where it be!

**Comment by jibe-b** [comment]
cc @csarven as I already had contact with you, but indeed I'd get reviews from anybody :)

**Comment by csarven** [comment]
It sounds like you have a specific set of applications in mind. Would you agree that perhaps we move the discussion over to https://github.com/linkedresearch/linkedresearch.org/issues or somewhere else?

**Comment by jibe-b** [comment]
Sounds sound!

**Comment by jibe-b** [comment]
Moved to https://github.com/linkedresearch/linkedresearch.org/issues/5
