### ISSUE TITLE
Broken links in the document

### ISSUE THREAD

**Issue by KMax** [csarven/ldn#66]
I see that some of the links to interesting materials are broken, e.g. a link to the implementation report (https://linkedresearch.org/ldn/tests/summary). Could it be fixed somehow?

**Comment by csarven** [comment]
Thanks for the heads-up.

Can you clarify at which URL the broken links appear as well as the specific links that appear to be broken?

**Comment by KMax** [comment]
Looks like it's so because of https://linkedresearch.org website which is inaccessible. See `curl` output:

```
[kolchinmax@thinkpad-kolchinmax task]$ curl https://linkedresearch.org/
curl: (7) Failed to connect to linkedresearch.org port 443: Connection refused
[kolchinmax@thinkpad-kolchinmax task]$ curl http://linkedresearch.org/
curl: (7) Failed to connect to linkedresearch.org port 80: Connection refused
[kolchinmax@thinkpad-kolchinmax task]$ 
```

> Can you clarify at which URL the broken links appear as well as the specific links that appear to be broken?

Just open https://github.com/w3c/ldn/blob/master/index.html and find all links having https://linkedresearch.org as the domain.

**Comment by csarven** [comment]
I'm not experiencing a connection issue - tested from different locations. Can you reproduce from a different machine?

**Comment by KMax** [comment]
Oh, that's true, I'm sorry that I didn't check it from other locations. It's not available from my provider in Russia, I guess the IP address is in some of the stupid stop lists. 

I can confirm that it's available from Frankfurt and Helsinki via VPN.
