### ISSUE TITLE
Add note regarding preference of JSON-LD

### ISSUE THREAD

**Issue by akuckartz** [csarven/ldn#7]
Something along these lines:

The LDP specification requires supporting Turtle and JSON-LD while the LDN specification only requires supporting JSON-LD. This implies that an implementation of LDN which is also conforming to LDP MUST support **both** JSON-LD and Turtle.

**Comment by csarven** [comment]
We tried to take this into account originally, but see the explicit mention at https://github.com/csarven/ldn/commit/ecf9910ea76e4e71e772a0cfaafa7ff1acaef468 for the receiver. Is that acceptable? Enough to close this issue?

To summarise ( @rhiaro correct me if I'm mistaken ) currently the document says:

Receiver MUST accept JSON-LD, and Turtle is a MUST in the case of LDP, and naturally anything else the receiver supports. Sender MUST be able to send in JSON-LD, and anything else it can that the receiver is willing to take. Consumer MUST be able to accept JSON-LD.

**Comment by rhiaro** [comment]
I don't think we need the mention of Turtle being a MUST for LDP. Obviously if someone has implemented LDP already they're reading the LDP spec and have already done that, we don't need to say it.

@csarven I have no idea what "and naturally anything else the receiver supports" means. "and anything else it can that the receiver is willing to take." is also strange and confusing.

@akuckartz, I think it's worth differentiating between LDP servers and LDP clients wrt to the serializations. LDP servers MUST (according to LDP spec) create resources in JSON-LD if they're POSTed with `application/ld+json`. So an existing LDP server would work with an LDN sender with no further changes. However, an existing LDP client would _not_ work with an non-LDP LDN receiver if the client only sends turtle and the receiver only accepts JSON-LD. But an LDP client would need other changes to be compatible with LDN anyway (eg. inbox discovery), so this is fine. So what we're saying is LDP _servers_ work out of the box as LDN receivers, but LDP _clients_ would require modification to be senders/consumers.

An LDN client which sends only JSON-LD _will_ work with an out-of-the-box LDP server which is acting as receiver. Does that clarify?

**Comment by csarven** [comment]
@akuckartz I've reverted my original change. Would you mind looking over again to see if we really have to say something explicit? LDP compliance is outside of the scope of LDN.

**Comment by rhiaro** [comment]
Closing because we don't need to talk about LDP compliance in the LDN spec
