### ISSUE TITLE
What to serve eventually when Turtle is received

### ISSUE THREAD

**Issue by csarven** [csarven/ldn#9]
One area which might need further explanation is what happens when the sender gives Turtle, receiver creates Turtle, but the Consumer asks for JSON-LD. Some options:
- Bump the requirements of the Consumer so that it can accept Turtle - this raises the bar too much, I don't fancy this
- Receiver re-serialises whatever it gets to JSON-LD - not too bad especially if it is willing to take other content-types.
- ?

**Comment by rhiaro** [comment]
The receiver reserialising as JSON-LD is implicit in the fact they MUST be able to return JSON-LD when requested. Doesn't matter how they store it internally.

**Comment by csarven** [comment]
Fair enough. This is a non-issue then. Closing.
